### ISSUE TITLE
PSGI Version 0.7Draft

### ISSUE THREAD

**Issue by ufobat** [supernovus/perl6-psgi#8]
The P6SGI specification is currently at version 0.7Draft. Is there a reason why this module is not yet updated?

Is this module supposed to work with the latest or with any version of the P6SGI specification? 

https://github.com/zostay/P6SGI

**Comment by supernovus** [comment]
The P6SGI support in this module was added a while ago. I have not been very active in the Perl 6 community in the last 3 years, so if there have been significant changes to the specification since it was implemented, then unless someone else has implemented them in one of the many pull requests, this module may be missing some features. It aims to support the full P6SGI specification, so at some point I will re-read the current documents and update the library for anything that may be missing.

**Comment by supernovus** [comment]
Updating it now, along with the Web library. They will support in order of preference, P6SGI 0.7Draft, P6SGI 0.4Draft, and PSGI Classic 1.0.

**Comment by supernovus** [comment]
See commit a68b27a for the implementation of this.
